name: Verify App

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v3
    
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                node-version: "18"
                cache: "npm"
    
            - name: Install dependencies
              run: npm ci --ignore-scripts
    
            - name: Run tests
              run: npm run test

    lint:
        name: Lint
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v3
    
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                node-version: "18"
                cache: "npm"
    
            - name: Install dependencies
              run: npm ci --ignore-scripts
    
            - name: Run linter
              run: npm run lint